language: python

matrix:
    include:
        - os: linux
          python: 2.7
          env: TOXENV=py27
        - os: linux
          python: 3.4
          env: TOXENV=py34
        - os: linux
          python: 3.5
          env: TOXENV=py35

install:
  - pip install tox
  - pip install coveralls

script:
  - tox

after_success:
    - if [[ $ENV == python=3.5* ]]; then
          coveralls;
      fi
