language: python

install:
  - pip install -r requirements/dev.txt
  - pip install tox-travis

script:
  - tox
  - coverage run --source pymonzo -m py.test
  - coverage report -m

after_success:
  - coveralls
